### ISSUE TITLE
Resolve Cannot find reference 'dir_util' in '__init__.py'

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris_firefox#1327]
Line `from distutils import dir_util` produces an import error: `Resolve Cannot find reference 'dir_util' in '__init__.py'`

Removing it and using `shutil.copytree()` instead of `dir_util.copy_tree()` will fix the problem

**Comment by mwobensmith** [comment]
Unfortunately, this caused an error on Mac (at least) where it could not copy the control center files on startup. Likely this API works a little differently than the one it is replacing. I had to reinstate the original logic with unrelated issue #1331 so that we could unbreak the build. We can investigate fixing this any time, since it's basically a cosmetic issue.
