### ISSUE TITLE
Give the Control Center the ability to save and re-run configurations

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#1419]
Once we start bringing on customers, we'll want the ability to run a hand picked set of test cases created by selecting them in the Control Center. We should offer the ability to save test run configurations and have the ability to call them up again in the future.

**Comment by psilaghi** [comment]
Great idea!
I'll start working on this.

**Comment by psilaghi** [comment]
So, I've analyzed this a bit. I'm going to need:
- UI button to 'Save configuration'
- URL where to send the settings to the server for saving them on the disk
- UI selector to choose from the saved configs

@mwobensmith what do you think?

**Comment by mwobensmith** [comment]
I was thinking that you were going to do this with a cookie on your side. On page startup, check for a cookie. If no cookie exists, just populate the page as we do now.

If cookie exists, it should contain serialized data about the UI state. You would then recreate the state from this cookie.

On close of page, you would update the cookie.

If we do this, no new UI is needed. The page automatically loads with the settings from the previously-used run. The only issue I see here is that one might want to start with default settings, in which case we'd want a "reset" button. I don't know if we need to go that far right now.

Do you think the above is reasonable?

**Comment by psilaghi** [comment]
So, you just want to save the UI state before the session ends. I thought we want to save multiple configurations and then be able to choose from a list the wanted configuration.
Indeed, your idea sounds good and simple, and might be enough for the moment, since there aren't so many settings to select right now. The problem is if you switch the browser and computer, you'll lost the settings.
@tracywalker what do you think?

**Comment by tracywalker** [comment]
I am not so concerned about sharing configs across machines.  If you store them in a file when the Control Center starts it can go get the list of available configs stored on that machine.  If needed, you could just copy and move the config with you on usb stick. 

Anyway,  I'd like our customers to be able to store setups by naming it something unique and be able to call it back at any time under a menu of Saved Test Configs or something like that.  Maybe I am overthinking this.  Maybe it is not even wanted.  We'll have to see what happens when users start running configs on a regular basis.

**Comment by mwobensmith** [comment]
We are going to rewrite all of this shortly, so I don't think we want to be too ambitious right now. I was thinking saving UI state would be the simplest way to achieve this. 

In December we will begin the process of redesigning the whole thing, based on what Iris currently does. Since we will be meeting with potential Iris users, we should be able to get their feedback on how important it is to be able to save settings, and that will influence our work in this direction.
