### ISSUE TITLE
Test case: Bug 1437880 - The "Remove Selected" button is not grayed out after a website is deselected.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3073]
https://testrail.stage.mozaws.net/index.php?/cases/view/145301

**Comment by pavelciapa** [comment]
Iris don't distinguish active and inactive buttons. 

![remove_selected_button_active](https://user-images.githubusercontent.com/45387203/59512521-6fa14280-8ea8-11e9-9a92-41aae863f680.png)
![remove_selected_button_inactive png](https://user-images.githubusercontent.com/45387203/59512522-6fa14280-8ea8-11e9-983d-2ac4e8460cb3.png)

Both images are found on `similarity(0.98)` and don't found on `exact()`

Critical to distinguish this two buttons for test case.

> 5 | Then click on "Site" from the table header. | 
> - The "Remove Selected" button is disabled. 
> - NOTE: In the builds affected by this bug the "Remove Selected" button is still enabled.
> 

p.s. `exact()` still don't work - https://github.com/mozilla/iris/issues/182

**Comment by ranjit-exalt** [comment]
Since Iris doesn't distinguish active and inactive buttons, I took an alternate approach instead of simply verifying the Active and inactive button images. Even at 100% pattern matching [exact()], Iris doesn't distinguish active and inactive buttons. Test case objective met with implemented alternate approach in #4255.

Test passed for all 4 OS.
