### ISSUE TITLE
Fix download_manager suite

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3482]
Update images that are not found

**Comment by pavelciapa** [comment]
Update few more images for download_manger suite

**Comment by tracywalker** [comment]
I believe we should get rid of using local files for the download manager test. If we can't come up with a way to host the pages/files that doesn't require Iris to use bootstrap to install the files then we shouls return to using the live website.

**Comment by tracywalker** [comment]
As part of this, please remove `download_manager_smoke.py`.  Because it downloads a Firefox build to the host machine and then the system opens the installer, this is unsuitable for Iris.  It's likely what is causing test runs to fail when running the download_manager suite.  

In addition, since the change to core package, this test suite needs some extra attention to get it back in complete working order.

**Comment by pavelciapa** [comment]
> 
> 
> As part of this, please remove `download_manager_smoke.py`. Because it downloads a Firefox build to the host machine and then the system opens the installer, this is unsuitable for Iris. It's likely what is causing test runs to fail when running the download_manager suite.
> 
> In addition, since the change to core package, this test suite needs some extra attention to get it back in complete working order.

- block `download_manager_smoke` tests
- working on each test individualy. OSx already done. 5-10 tests on onther OS left

**Comment by tracywalker** [comment]
Just delete download_manager_smoke

**Comment by pavelciapa** [comment]
> Just delete download_manager_smoke

- deleted

**Comment by pavelciapa** [comment]
Fixed all tests for osx and win10. 

Few issuses are hard to fix for win7 and linux. Resolve this in further commits. 

At the moment **donwload_manager** suite can be merged into dev, and run on win10 and osx.

**Comment by tracywalker** [comment]
Pavel,  I set up a site with our download manager test page.  It's at https://irisfirefoxtestfiles.netlify.com.  Please make the download tests use this instead of local_web. Also, several tests in this suite employ the  select_throttling() function.  You should be able to safely remove them from tests, as files will be downloading over live network again.

**Comment by tracywalker** [comment]
While working to improve the download_cancel_retry test in the Nightly test target, I discovered some useful about:configs.  In each of the download tests that access the download button from the NavBar, we should set, in the ```@pytest.mark.details```
```
"browser.download.autohideButton": False,
"browser.download.panel.shown": True,
```

**Comment by tracywalker** [comment]
Ranjit, please see my above comment about the settings these tests should.  Also.  the tests are still very flakey,  we may have to re-implement using the dev tools to throttle page loading.

**Comment by ranjit-exalt** [comment]
#4271 created to re-implement the download logic. Closing, as objectives of this issue, will be completed in #4271.
