### ISSUE TITLE
Update tests in 'zoom_indicator' suite according to UI changes  

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3795]

**Comment by pavelciapa** [comment]
Can't reproduce failures. All tests pass (25/25)

**Comment by tracywalker** [comment]
There we're a bunch of errors reported by irishub for 'Could not create create region for URL bar.'  I believe this is due to a change I made Friday in what pattern NavBar.HAMBURGER_MENU uses.  I will fix it in this issue.  Doing so should also fix test having the error 'Can't find the "hamburger menu" in the page, aborting test.'

**Comment by tracywalker** [comment]
I had been experimenting with the patterns available and failed to return the pattern reference to the original pattern.  This should fix ~30 errors in recent test runs.
