### ISSUE TITLE
Investigate and fix restart_firefox() sending quit to terminal on OSX

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4020]
I am running a test the calls restart_firefox().  The browser is shut down correctly and starts back up correctly. However,  in between, while Firefox is not running, keystrokes or something is being set to the terminal that causes it to put up a dialog asking if you want to terminate it.  I think this happening in firefox_app/fx_browser.py > stop()

**Comment by tracywalker** [comment]
If I comment out line 333 in fx_browser.py, the problem goes away and the test still runs successfully. I don't quite understand what is going on with this stop() function, but the logic in the else must not be right if it's sending command+Q to terminal.

Matt, when you have some time, can you take a look?  The test I am running is previous_session_can_be_restored_from_firefox_menu.

**Comment by mwobensmith** [comment]
The problem is in the test itself, line 33 onward:

```
        if OSHelper.is_mac():
            quit_firefox()
        elif OSHelper.is_linux():
            click_hamburger_menu_option("Quit")
        else:
            click_hamburger_menu_option("Exit")

        firefox.restart()
```
This sends the first CMD+Q to quit Firefox, and then calls the `restart` function, which will do this a second time. At that point, the browser has already been quit by the first call, and the second call is interpreted by the terminal, which is now active.

It seems to me that the test should not call `quit_firefox` if it intends to call `restart`, since the latter already handles the quit part. What do you think @tracywalker ?

**Comment by tracywalker** [comment]
Agreed.  Thank you for investigating.  I'll fix this right away in the test.
