### ISSUE TITLE
Shutdown method fails to close Firefox

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#4150]
I'm finding on all three of my machines (Mac OS, Windows 10, and Ubuntu 16.04) that Iris is failing to shutdown Firefox resulting in multiple instances being open.

Screenshot from my Mac:
![IMG_20191104_122946](https://user-images.githubusercontent.com/766595/68156089-00091e00-ff43-11e9-9999-b2c2c5a90656.jpg)

**Comment by tracywalker** [comment]
Matt,  can you take a look.  The shutdown (or startup) method shouldn't allow a test run to get in this sort of state

**Comment by mwobensmith** [comment]
Does this happen when just running one test? The whole test run? Every test or just some?

I am a bit at a loss to explain why this would just happen for you and not Taskcluster/Exalt, who would have been blocked by this.

I need more info to help me debug this, but will begin to look at it on my own now.

**Comment by mwobensmith** [comment]
Some of these failures have to do with an orphaned Library window. When it's open, we can get into a situation where our current "quit_firefox" logic doesn't work.

For example, the test "about_downloads_accurate_data.py" exhibits issues on at least two platforms.

* On Mac, the Library window is open, and we attempt to quit Firefox (Key.ESC and then CMD-Q). This happens during a file download, which prompts a modal dialog asking "Cancel All Downloads?". Attempts to CMD-Q here fail, and we've already used the Key.ESC before getting here, so we're stuck. We'd be unstuck if we could hit the escape key again. However, the Firefox instance remains open.

* On Linux, the Library window is open, and the only way it appears to be able to exit is via Ctrl-W. The current Key.ESC plus Ctrl-Q don't work on this child window. Again, due to this orphaned window, we are stuck with this Firefox instance.

Just considering the above, there are ways we can make the test cases themselves a bit more flexible in handling the behavior. Additionally, we can alter the quit_firefox helper function to handle it as well. Not sure where we should make these changes.

I think we should solve the above problem first, and then re-run the suite to find other causes of persistent Firefox instances.

**Comment by ashughes1** [comment]
One possible reason for getting in to this orphaned state: the 10MB and 20MB downloads never seem to end and don't download any bits. It's possible there's something wrong here on the test site that's preventing these downloads from completing and that the test expects them to finish. 

Perhaps adding some logic to treat the downloads not completing with an assertion and cleaning up if the assertion is thrown? In any case we should not be leaving Firefox in this state whether expected or not.

**Comment by mwobensmith** [comment]
Talking to @tracywalker it seems the first thing we should do is guarantee that a test case finishes and quits Firefox, no matter what the outcome of the test itself. We need to make sure that the next test starts without an orphaned instance of Firefox sticking around. I am going to focus on this problem and see if it solves this and a few other use cases.

**Comment by mwobensmith** [comment]
In `main.py`, line 382, we used to have this:
```
item.funcargs["firefox"].browser.runner.stop()
```

However, the `runner` is being called on a `browser` object that may or may not exist, and this appears to have no effect. There is a `try/except` statement around this whole block of code, but if it fails, we let it `pass`. 

When I correct this statement like so, it correctly quits Firefox with each test and seems to solve the problem:
```
item.funcargs["firefox"].runner.stop()
```

This is for Mac/Linux only. The Windows logic is unaffected.

Let's try this fix and see how far it gets us.

**Comment by ashughes1** [comment]
I've just finished re-running the download manager tests on the dev branch as a reduced testcase and verify the Firefox processes are now being shutdown properly on Windows 10, Mac OS 10.15 and Ubuntu 16.04.

**Comment by tracywalker** [comment]
Excellent!
