### ISSUE TITLE
Improve Iris email reports for Release QA

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#4165]
I would like to propose some changes to the email reports so that they are more useful to Release QA or anyone else consuming these reports. I will own implementing these changes but I'd like to solicit feedback before I go to the trouble of writing the code.

Here is what the report currently looks like:
```
Repo_details:
 Branch_name: dev
 Branch_head: c631344281e0db2362052efc87860cf927013ae4
 Test_Run_Details:
------------------------------------------------------------------------------------------------Test Report-------------------------------------------------------------------------------------------------
Application: Firefox, Platform: linux, fx_version: 71.0, fx_build_id: 20191104135555, channel: beta
Passed: 254, Failed: 204, Skipped: 54, Errors 41  -- Total: 553                                                                                                                     Total time: 11:36:30.051

The following tests did not pass:
no_search_form_history.py

no_third_party_cookies.py

saved_cc_available_in_private_session.py
```

My suggested improvements are as follows:
* **Platform**: include OS version so that I know for example that this was run on Ubuntu 16.04 or Debian 10, not just "linux".
* **Locale**: include the locale of the build tested so that we know this was en-US, de, etc.
* **Test Group**: include the testgroup (or folder) the test comes from so it's more easily discoverable in the test folder structure.
* **Testrail ID**: when listing a test include the Testrail ID as specified in the test so that the consumer of the result can easily refer to that ID in Testrail.
* **Testrail URL**: when listing a test, also include the URL to the testcase in Testrail based on the above referenced ID. When viewing this through an email client (such as GMail) the URLs will render clickable which will make this much easier from a workflow standpoint.

Here is a mockup of what this might look like:
```
Repo_details:
 Branch_name: dev
 Branch_head: c631344281e0db2362052efc87860cf927013ae4
 Test_Run_Details:
------------------------------------------------------------------------------------------------Test Report-------------------------------------------------------------------------------------------------
Application: Firefox, Platform: linux (Ubuntu 16.04 x86_64; Linux 4.15.0-65-generic), fx_version: 71.0, fx_build_id: 20191104135555, locale: en-US, channel: beta
Passed: 254, Failed: 204, Skipped: 54, Errors 41  -- Total: 553                                                                                                                     Total time: 11:36:30.051

The following tests did not pass:
[C105209] anti_tracking/no_search_form_history.py [https://testrail.stage.mozaws.net/index.php?/cases/view/105209]
[C106156] anti_tracking/no_third_party_cookies.py [https://testrail.stage.mozaws.net/index.php?/cases/view/106156]
[C101667] anti_tracking/saved_cc_available_in_private_session.py [https://testrail.stage.mozaws.net/index.php?/cases/view/101667]
```

**Comment by mwobensmith** [comment]
Currently the email report logic lives in core code, and you want to change only the `iris_firefox` project. This will probably require two major work items in each target's  `main.py` file:


* You should import and subclass `EmailClient` from `moziris.email_report.email_client`, and then override the method(s) that do the email formatting to change it the way you want.

* The logic in the target that calls the email report is in `moziris/base/target.py`, starting at line 115 within the `pytest_sessionfinish` function. Since this function is called from `targets/firefox/main.py`, line 256, you may have to remove that call and add the contents of that function inline here (from the base class function), omitting the call to the superclass `submit_email_report` function and substituting with your new one.
