### ISSUE TITLE
Some tests disregard being skipped

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#4192]
I have noticed that `enabled=False,` in `pytest.mark.details()` is being ignored for some tests locally.

In an effort to establish a GREEN baseline for running tests locally on my test machines I've started disabling all the tests that fail by adding `enabled=False,` to the end of `pytest.mark.details()` in each test. Most tests appear to be respecting this but there are some tests which ignore this statement and run anyway.

These tests are:
* firefox/in_browser_pdf/pdf_navigation.py
* firefox/in_browser_pdf/pdf_predefined_zoom_levels.py
* firefox/in_browser_pdf/presentation_mode_available.py

There may be others but I'll update this as I find them.

**Comment by mwobensmith** [comment]
The problem is that these tests - and a few others - have a misnamed test function. They use `test_run` instead of `run`, and while we still end up calling the function, the fact that the test author(s) named this wrong messes up our test skip logic. 

Add to above list:
* pdf_zoom.py
* image_rich_properly_opened_and_navigated.py

**Comment by tracywalker** [comment]
I'll update the tests affected by this.
