### ISSUE TITLE
Fix default prefs for profiles

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4197]
I just fixed issue #4194 to stop the dialog from appearing in private browsing windows. I put the correct config in settings.py.  

```
        # Disable the extensions in private window dialog
        "extensions.privatebrowsing.notification": True,
```
But the dialog still appears in tests. 

 If I put the config directly in a test with:
```
preferences={"extensions.privatebrowsing.notification": True,}
```
the setting works correctly to disable the dialog.

Try it in private_browsing/history_remembered.py test.

**Comment by mwobensmith** [comment]
See `targets/firefox/firefox_app/fx_browser.py` lines 166-169. Right now we only apply these default prefs for profile type `BRAND_NEW`. I guess we decided that if you use a reserved, canned profile that we assume you already have your prefs set the way you want. 

If you want this changed, let me know, easy to do.

**Comment by tracywalker** [comment]
We do need a way to implement configs to deal with dialogs that have been added to Firefox UI since the creation of our profiles.

**Comment by mwobensmith** [comment]
As per conversation with @tracywalker it appears that we have somehow inverted our logic for what prefs get applied to various profiles.

It seems that we should document how we want it to be from here forward. 
* `BRAND_NEW` should have no custom prefs, default or otherwise. It should behave like a clean, new profile.
* `LIKE_NEW` should be as above, but with custom prefs applied that disable certain first-run features that interfere with our tests, such as modal dialogs on close. 
* `TEN_BOOKMARKS` should be the same as `LIKE_NEW` but with ten bookmarks.

Do you agree @tracywalker ?

**Comment by tracywalker** [comment]
Yes, that seems like the right way.

**Comment by mwobensmith** [comment]
The initial change to profiles is trivial. I'll make that shortly. The bigger change is likely to happen when you run the test suite and observe test cases that use `BRAND_NEW`. They need to account for the lack of default prefs, or use a different profile such as `LIKE_NEW` instead.

**Comment by mwobensmith** [comment]
@tracywalker Branch `issue_4197` exists and can be tested now.

**Comment by tracywalker** [comment]
With all of the noise on Iris test runs right now, we will hold off on testing this until we can more easily determine what tests are affected.

**Comment by tracywalker** [comment]
I picked this up in the dependent test case work.
