### ISSUE TITLE
Fix ff_can_be_set_never_remember_history

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#4302]
Fix ff_can_be_set_never_remember_history

**Comment by ranjit-exalt** [comment]
Test script is still failing in Windows 10. Screenshots attached below: 

![image](https://user-images.githubusercontent.com/54833244/71589450-f10da900-2b4a-11ea-97ce-f4efb750fda6.png)

Debug image: 
![image](https://user-images.githubusercontent.com/54833244/71589476-01be1f00-2b4b-11ea-9a89-6508fd1cbd24.png)

Since PR #4372 was created by @spronoza, assigning it to him.
