### ISSUE TITLE
Menu Bar not displayed for Linux in Toolbar door hanger in customize page

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4586]
As per the test case, defined in [https://testrail.stage.mozaws.net/index.php?/cases/view/118186](https://testrail.stage.mozaws.net/index.php?/cases/view/118186)
 in the 3rd Step expected is that, the Menu bar option to be displayed above the Tab bar for Windows 10 and Linux OS, but it is displaying for Windows 10 only and not for Linux
![Screenshot from 2020-01-21 15-36-21](https://user-images.githubusercontent.com/54833244/72797335-ebe1dc80-3c66-11ea-80d6-accd92926105.png)

**Comment by obotisan** [comment]
I tried to reproduce the issue on Ubuntu 16.04 x64 and Ubuntu 18.04 x64 using Firefox 73.0b7, but I couldn't. I even change the settings from the OS in order to show the menu bar on the title bar, but didn't manage to reproduce is.
Can you please give me some additional information, like on what platform you reproduced this and have you made some changes in the OS settings?

**Comment by ranjit-exalt** [comment]
This issue was there is Firefox 72. It's working fine in 73.0b8, so closing this issue.
