### ISSUE TITLE
Develop a robust cross platform system file picker API

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#675]
We need to develop a helper that can handle most system file picker use cases.

**Comment by tracywalker** [comment]
Ionut,  when you have finished bookmark test work. Please feel free to begin exploring this issue.

**Comment by IonutBudeanu** [comment]
I think I found a solution regarding this file picker system. We can do this using actual support that Iris offers.

I investigated a little bit how exactly the search items mechanism works on our 3 supported platforms and i saw that we can interact only with the UI in order to find the searched backup files.

That's being said I'll add a new object pattern that includes all the needed patterns for this system and i'll try to build a helper function called `restore_bookmarks_from_an_external_file()`.

For the moment this is just an experimental case.

**Comment by tracywalker** [comment]
iris_firefox/targets/firefox/firefox_ui/helpers/file_picker_utils.py has been developed. Any additional needs in file picking should be added there.
